### ISSUE TITLE
Any plans to support Merge operator?

### ISSUE THREAD

**Issue by rubencaro** [urbint/rox#13]
Great job!
Just to be informed, are there any plans to support Merge operator?

https://github.com/facebook/rocksdb/wiki/Merge-Operator

**Comment by rschmukler** [comment]
I imagine this would be quite difficult to support because rustler (the rust bindings library this is built on) doesn't provide a way to call Erlang / Elixir functions from the Rust side of things. Digging deeper and it seems like this functionality might not even be possible with the [raw nif c-library](http://erlang.org/doc/man/erl_nif.html#ErlNifFunc) so I don't think it's possible at the moment.

Definitely interested if anyone sees a solution.

**Comment by rubencaro** [comment]
Thanks for the quick response.
